### ISSUE TITLE
run demo.py error

### ISSUE THREAD

**Issue by jinxinbao** [xiaoxingzeng/DF2Net#18]
Hi, I am very interested in your work,but when i run the code it doesn't works ,and can you help me? looking forward to your reply!
run python demo.py,it appers:
Traceback (most recent call last):
  File "demo.py", line 115, in <module>
    face_reconstruction(model_path)
  File "demo.py", line 83, in face_reconstruction
    for i, (input,img_name) in enumerate(demo_loader):
  File "/home/li/anaconda3/envs/pt1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 568, in __next__
    return self._process_next_batch(batch)
  File "/home/li/anaconda3/envs/pt1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
cv2.error: Traceback (most recent call last):
  File "/home/li/anaconda3/envs/pt1/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/li/anaconda3/envs/pt1/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/li/dataset/DF2Net-master/data_load.py", line 121, in __getitem__
    crop_face_mask(path)
  File "/media/li/dataset/DF2Net-master/data_load.py", line 42, in crop_face_mask
    raw_gray = cv2.cvtColor(raw_im, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.3.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by SAHIB-MAJITHIA** [comment]
It is because the image you are loading is empty. You need to recheck the name of the image.
 It worked for me by using : img_dir+img_name.replace('.png','_mask.png')[:-1]
